import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import clsx from "clsx";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Купи работу",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "body")}>
        <Header theme="default" />
        <div className="page">
          {children}
        </div>
        <Footer theme="default" />
      </body>
    </html>
  );
}
