import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import clsx from "clsx";
import { useContext } from "react";
import ThemeContext, { ThemeProvider } from "@/context/ThemeContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Купи работу",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={clsx(inter.className, "body")}>
          <Header />
          <div className="container">
            {children}
          </div>
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  );
}
